name: cd-prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render Production Deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PROD_URL }}"

      - name: Confirm deployment
        run: echo "Deployment to production triggered at $(date)"